[package]
name = "giga-chess-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["http2", "ws"] }
giga-chess = "0.8.0"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
utoipa = "5.3.1"
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
serde = { version = "1.0.219", features = ["derive"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
thiserror = "2.0.12"
r2d2 = "0.8.10"
diesel = { version = "2.2.10", features = ["postgres", "r2d2"] }
dotenvy = "0.15.7"
