FROM rust:1.87-slim

RUN apt-get update && apt-get install -y \
    curl \
    pkg-config \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

WORKDIR /app
COPY . .

EXPOSE 8869