services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - ../config/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8869:8869"
    env_file:
      - ../config/.env.prod
    depends_on:
      - db
    command: >
      sh -c "
        diesel migration run
        cargo install --path . --bin cli
        cargo run --release
      "

volumes:
  postgres_data: